apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: $GKE_DEPLOYMENT_NAME
spec:
  replicas: 1
  revisionHistoryLimit: 5
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: $GKE_DEPLOYMENT_NAME
        env: staging
    spec:
      containers:
      - name: $GKE_DEPLOYMENT_NAME
        image: "gcr.io/google-samples/hello-app:2.0"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            requests:
               cpu: "$GKE_POD_CPU"
               memory: "$GKE_POD_MEMORY"
            limits:
               cpu: "100m"
               memory: "100Mi"
        # health checks self healing check port 80 response 200,
        # if containers error (400-500) kubernetes restart the pod
#        readinessProbe:
#          httpGet:
#            path: /
#            port: 80
#          initialDelaySeconds: 25
#          timeoutSeconds: 10
#          periodSeconds: 5
#        livenessProbe:
#           httpGet:
#             path: /
#             port: 80
#           initialDelaySeconds: 25
#           periodSeconds: 5
